[workspace]
resolver = "2"
members = [
	"ruffd",
	"ruffd-core",
	"ruffd-types",
	"ruffd-macros",
]
exclude = []

[workspace.package]
edition = "2021"
rust-version = "1.64"
license = "MIT"
authors = ["Seamus Mulholland-Patterson <seamus1103@gmail.com>"]
