[package]
name = "ruffd-types"
version = "0.0.1"
edition = "2021"

[dependencies]
lsp-types = "0.93"
ruff = { git = "https://github.com/charliermarsh/ruff", rev = "417764d309bb444cafc088f12b84ff3a95424e41" }
tokio = { version = "1.20", features = ["full"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
