name: Ruffd CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ruffd-core, ruffd-macros, ruffd-types, ruffd]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/cache@v3
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo build --release

  lint:
    name: Lint ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ruffd-core, ruffd-macros, ruffd-types, ruffd]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: actions/cache@v3
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Lint ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo clippy

  test:
    name: Test ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ruffd-core, ruffd-macros, ruffd-types, ruffd]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions/cache@v3
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Test ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo test

  check_fmt:
    name: Check formatting for ${{ matrix.crate }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate: [ruffd-core, ruffd-macros, ruffd-types, ruffd]
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - uses: actions/cache@v3
        env:
          cache-name: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Check formatting for ${{ matrix.crate }}
        working-directory: ${{ matrix.crate }}
        run: cargo fmt --check
